import { Event, TeamMember, Resource, Announcement, GalleryImage, FormEntry, Contributor } from "./types";

export const fallbackEvents: Event[] = [
  // {
  //   id: "1",
  //   title: "Career in IT",
  //   date: "2024-05-15",
  //   time: "10:00 AM",
  //   location: "GCES Auditorium",
  //   description: "An interactive session exploring diverse career paths in Information Technology.",
  //   image_url: "/Carousel/Career in IT.jpg",
  //   register_link: "",
  //   status: "past",
  // },
  // {
  //   id: "2",
  //   title: "Software Testing Workshop",
  //   date: "2024-07-20",
  //   time: "2:00 PM",
  //   location: "Lab 3",
  //   description: "Hands-on workshop on modern software testing practices and tools.",
  //   image_url: "/Carousel/Software Testing.jpg",
  //   register_link: "",
  //   status: "past",
  // },
  // {
  //   id: "3",
  //   title: "WordPress x React",
  //   date: "2024-08-10",
  //   time: "11:00 AM",
  //   location: "Seminar Hall",
  //   description: "Learn how to integrate WordPress as a headless CMS with React.",
  //   image_url: "/Carousel/WordpressXReact.jpg",
  //   register_link: "",
  //   status: "past",
  // },
];

export const fallbackTeam: TeamMember[] = [
  {
    id: "1",
    name: "Aashik",
    role: "President",
    year: "4th Year",
    branch: "Software Engineering",
    bio: "Leading the IT club with a vision for innovation.",
    image_url: "/team_members/aashik.jpg",
    github: "",
    linkedin: "",
    email: "",
    order: 1,
  },
  {
    id: "2",
    name: "Suchana",
    role: "Vice President",
    year: "3rd Year",
    branch: "Software Engineering",
    bio: "Managing club operations and organizing major events.",
    image_url: "/team_members/suchana.jpg",
    github: "",
    linkedin: "",
    email: "",
    order: 2,
  },
  {
    id: "3",
    name: "Abhisheq",
    role: "Technical Lead",
    year: "3rd Year",
    branch: "Software Engineering",
    bio: "Guiding the technical direction of club projects.",
    image_url: "/team_members/abhisheq.png",
    github: "",
    linkedin: "",
    email: "",
    order: 3,
  },
  {
    id: "4",
    name: "Bishal",
    role: "Event Coordinator",
    year: "3rd Year",
    branch: "Software Engineering",
    bio: "Ensuring all our workshops and events run flawlessly.",
    image_url: "/team_members/bishal.jpg",
    github: "",
    linkedin: "",
    email: "",
    order: 4,
  },
  {
    id: "5",
    name: "Mamata",
    role: "Design Lead",
    year: "2nd Year",
    branch: "Software Engineering",
    bio: "Creating beautiful UI/UX for all our materials.",
    image_url: "/team_members/mamata.jpg",
    github: "",
    linkedin: "",
    email: "",
    order: 5,
  },
  {
    id: "6",
    name: "Mayuk",
    role: "Content Creator",
    year: "2nd Year",
    branch: "Software Engineering",
    bio: "Documenting our journey and managing content.",
    image_url: "/team_members/mayuk.jpg",
    github: "",
    linkedin: "",
    email: "",
    order: 6,
  },
  {
    id: "7",
    name: "Prapti",
    role: "PR Manager",
    year: "2nd Year",
    branch: "Software Engineering",
    bio: "Handling public relations and outreach.",
    image_url: "/team_members/prapti.jpg",
    github: "",
    linkedin: "",
    email: "",
    order: 7,
  },
  {
    id: "8",
    name: "Rozy",
    role: "Treasurer",
    year: "3rd Year",
    branch: "Software Engineering",
    bio: "Managing the club finances.",
    image_url: "/team_members/rozy.jpg",
    github: "",
    linkedin: "",
    email: "",
    order: 8,
  },
  {
    id: "9",
    name: "Swarnima",
    role: "Executive Member",
    year: "2nd Year",
    branch: "Software Engineering",
    bio: "Supporting club initiatives.",
    image_url: "/team_members/swarnima.jpg",
    github: "",
    linkedin: "",
    email: "",
    order: 9,
  },
];

export const fallbackResources: Resource[] = [
  // {
  //   id: "1",
  //   title: "React Documentation",
  //   type: "docs",
  //   link: "https://react.dev",
  //   description: "Official React documentation.",
  //   tags: "react, frontend",
  // },
];

export const fallbackAnnouncements: Announcement[] = [
  {
    id: "1",
    title: "New Website",
    content: "Welcome to the new GCES IT Club website!",
    date: "2026-05-14",
    active: "true",
  },
];

export const fallbackGallery: GalleryImage[] = [
  { id: "1", image_url: "/Carousel/Career in IT.jpg", title: "Career in IT Workshop", order: 1 },
  { id: "2", image_url: "/Carousel/Software Testing.jpg", title: "Software Testing Session", order: 2 },
  { id: "3", image_url: "/Carousel/WordpressXReact.jpg", title: "WordPress and React Integration", order: 3 },
];

export const fallbackForms: FormEntry[] = [];
export const fallbackContributors: Contributor[] = [];
